name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Run Lint
        run: ./gradlew lintDebug
      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Run build debug
        run: ./gradlew assembleDebug
      - name: Run Tests
        run: ./gradlew :Provider:testDebugUnitTest --no-daemon --stacktrace
      - name: Run build release
        run: ./gradlew assembleRelease
