on:
  push:
    branches:
      - main

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest

    # Release-please creates a PR that tracks all changes
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          command: manifest
          default-branch: main

      - name: Dump Release Please Output
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJson(steps.release.outputs) }}
        run: |
          echo "$RELEASE_PLEASE_OUTPUT"

    # Outputs are namespaced by package when using a manifest in Release Please
    outputs:
      release_created: ${{ steps.release.outputs['Provider--release_created'] }}
      # Version doesn't include `v` as a prefix. This is undocumented
      version: ${{ steps.release.outputs['Provider--version'] }}
      upload_url: ${{ steps.release.outputs['Provider--upload_url'] }}

  kotlin-release:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      # The logic below handles the github release:
      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/checkout@v4
        with:
            ref: ${{ needs.release-please.outputs.release_tag_name }}

      - name: Configure GPG Key
        run: |
            echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import --no-tty --batch --yes
            gpg --pinentry-mode=loopback --passphrase $GPG_SIGNING_KEY_PASSWORD --export-secret-key $GPG_SIGNING_KEY_ID > ~/.gnupg/secring.gpg
        env:
            GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
            GPG_SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: Add signing secrets to gradle.properties
        run: |
            mkdir ~/.gradle/
            echo "signing.keyId=$GPG_SIGNING_KEY_ID" >> ~/.gradle/gradle.properties
            echo "signing.password=$GPG_SIGNING_KEY_PASSWORD" >> ~/.gradle/gradle.properties
            echo "signing.secretKeyRingFile=/home/runner/.gnupg/secring.gpg" >> ~/.gradle/gradle.properties
        env:
            GPG_SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}
            GPG_SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Publish to Sonatype
        env:
          OF_KOTLIN_RELEASE_VERSION: ${{ needs.release-please.outputs.version }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew :Provider:publish --no-daemon --stacktrace

      - name: Clean up signing secrets
        run: rm ~/.gradle/gradle.properties

